'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import api from '@/lib/api'
import type { Client, TradeRecommendation } from '@/types'

export default function TradingOverviewPage() {
  const [clients, setClients] = useState<Client[]>([])
  const [recommendations, setRecommendations] = useState<TradeRecommendation[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async () => {
    try {
      setLoading(true)
      const [clientsData, recsData] = await Promise.all([
        api.clients.list(),
        api.trading.getRecommendations(undefined, undefined, 100),
      ])
      setClients(clientsData)
      setRecommendations(recsData.recommendations)
    } catch (err: any) {
      console.error('Failed to fetch data:', err)
      setError(err.detail || 'Failed to load data')
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
          <p className="mt-4 text-gray-600">Loading trading data...</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6">
        <h3 className="text-lg font-medium text-red-800">Error Loading Trading Data</h3>
        <p className="mt-2 text-sm text-red-700">{error}</p>
      </div>
    )
  }

  const pendingRecs = recommendations.filter((r) => r.status === 'pending')
  const approvedRecs = recommendations.filter((r) => r.status === 'approved')

  // Group recommendations by client
  const recsByClient = recommendations.reduce((acc, rec) => {
    if (!acc[rec.client_id]) {
      acc[rec.client_id] = []
    }
    acc[rec.client_id].push(rec)
    return acc
  }, {} as Record<number, TradeRecommendation[]>)

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Trading Overview</h1>
        <p className="mt-2 text-gray-600">
          View and manage trade recommendations across all clients
        </p>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div
          className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"
          title="Total trade recommendations generated by the ML/RL system across all clients"
        >
          <p className="text-sm font-medium text-gray-500">Total Recommendations</p>
          <p className="mt-2 text-3xl font-bold text-gray-900">{recommendations.length}</p>
        </div>
        <div
          className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"
          title="Trade recommendations awaiting approval before execution. Review and approve trades on client pages."
        >
          <p className="text-sm font-medium text-gray-500">Pending Approval</p>
          <p className="mt-2 text-3xl font-bold text-yellow-600">{pendingRecs.length}</p>
        </div>
        <div
          className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"
          title="Approved trade recommendations ready to be executed through your brokerage"
        >
          <p className="text-sm font-medium text-gray-500">Ready to Execute</p>
          <p className="mt-2 text-3xl font-bold text-green-600">{approvedRecs.length}</p>
        </div>
      </div>

      {/* Clients with Trading */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200">
        <div className="px-6 py-4 border-b border-gray-200">
          <h2 className="text-lg font-semibold text-gray-900">Clients</h2>
        </div>
        <div className="divide-y divide-gray-200">
          {clients.length === 0 ? (
            <div className="px-6 py-8 text-center text-gray-500">
              No clients found. Add clients to get started.
            </div>
          ) : (
            clients.map((client) => {
              const clientRecs = recsByClient[client.client_id] || []
              const pendingCount = clientRecs.filter((r) => r.status === 'pending').length
              const approvedCount = clientRecs.filter((r) => r.status === 'approved').length

              return (
                <div key={client.client_id} className="px-6 py-4 hover:bg-gray-50 transition-colors">
                  <div className="flex items-center justify-between">
                    <div>
                      <Link
                        href={`/clients/${client.client_id}/trading`}
                        className="text-lg font-medium text-blue-600 hover:text-blue-700"
                      >
                        {client.first_name} {client.last_name}
                      </Link>
                      <p className="text-sm text-gray-500">{client.email}</p>
                      {clientRecs.length > 0 && (
                        <p className="text-sm text-gray-600 mt-1">
                          {clientRecs.length} recommendation{clientRecs.length !== 1 ? 's' : ''}
                          {pendingCount > 0 && (
                            <span className="ml-2 text-yellow-600">
                              • {pendingCount} pending
                            </span>
                          )}
                          {approvedCount > 0 && (
                            <span className="ml-2 text-green-600">
                              • {approvedCount} approved
                            </span>
                          )}
                        </p>
                      )}
                    </div>
                    <Link
                      href={`/clients/${client.client_id}/trading`}
                      title="Generate ML/RL-optimized trade recommendations for this client's portfolio"
                      className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                    >
                      Generate Trades
                    </Link>
                  </div>
                </div>
              )
            })
          )}
        </div>
      </div>

      {/* Recent Recommendations */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200">
        <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Recent Recommendations</h2>
          <Link
            href="/trading/history"
            title="View all executed trades with their order status and fill prices"
            className="text-sm font-medium text-blue-600 hover:text-blue-700"
          >
            View Execution History →
          </Link>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Client
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Portfolio
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Trades
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Turnover
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Status
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Created
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {recommendations.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-6 py-8 text-center text-gray-500">
                    No recommendations yet. Select a client above to generate recommendations.
                  </td>
                </tr>
              ) : (
                recommendations.slice(0, 20).map((rec) => {
                  const client = clients.find((c) => c.client_id === rec.client_id)
                  return (
                    <tr key={rec.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {client ? (
                          <Link
                            href={`/clients/${client.client_id}/trading`}
                            className="text-blue-600 hover:text-blue-700"
                          >
                            {client.first_name} {client.last_name}
                          </Link>
                        ) : (
                          `Client ${rec.client_id}`
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {rec.rl_portfolio_name}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {rec.total_trades}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {(rec.expected_turnover * 100).toFixed(1)}%
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                            rec.status === 'pending'
                              ? 'bg-yellow-100 text-yellow-800'
                              : rec.status === 'approved'
                              ? 'bg-green-100 text-green-800'
                              : rec.status === 'executed'
                              ? 'bg-blue-100 text-blue-800'
                              : rec.status === 'rejected'
                              ? 'bg-red-100 text-red-800'
                              : 'bg-gray-100 text-gray-800'
                          }`}
                        >
                          {rec.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(rec.created_at).toLocaleDateString()}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <Link
                          href={`/clients/${rec.client_id}/trading`}
                          className="text-blue-600 hover:text-blue-700"
                        >
                          View →
                        </Link>
                      </td>
                    </tr>
                  )
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
